BaseURL = "https://www.mywebsite.com/"
languageCode = "en-us"
title = "New Challenge Ministries"
theme = "goodtrepreneur"
description = "This is meta description"
relativeURLS = true

############################# Navigation ##############################
[menu]
  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 1

  [[menu.main]]
    identifier = "volunteer"
    name = "Volunteer"
    url = "/volunteer/"
    weight = 2

  [[menu.main]]
    identifier = "corporate"
    name = "Corporate"
    url = "/corporate/"
    weight = 3

  [[menu.main]]
    identifier = "donate"
    name = "Donate"
    url = "/donate/"
    weight = 4
