BaseURL = "https://testing.goodtrepreneur.com/"
languageCode = "en-us"
title = "New Challenge Ministries"
theme = "goodtrepreneur"
description = "New Challenge Ministries"
relativeURLS = true

############################# Navigation ##############################
[menu]
  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 1

  [[menu.main]]
    identifier = "volunteer"
    name = "Volunteer"
    url = "/volunteer/"
    weight = 2

  [[menu.main]]
    identifier = "sponsor"
    name = "Sponsor"
    url = "/sponsor/"
    weight = 3

  [[menu.main]]
    identifier = "donate"
    name = "Donate"
    url = "/donate/"
    weight = 4
